##################################################
# WARNING
# This file is autogenerated by tools/update-deps
# from dependencies.yaml
##################################################

requires 'Storable', '>= 3.06';

feature 'cover' => sub {
    requires 'Devel::Cover';
    requires 'Devel::Cover::Report::Codecov';
};
on 'develop' => sub {
    requires 'Code::TidyAll';
    requires 'Perl::Critic';
    requires 'Perl::Critic::Community';
    requires 'Perl::Tidy', '== 20230912';
};
