---
name: ci
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Static checks, unit- and integration tests
        run: |
          sudo apt-get -y install libperl-critic-perl
          make test
